language: ruby
rvm:
  - 2.1.0
  - 2.0.0
env:
  - "RAILS_VERSION=4.0"
  - DB=sqlite
#  - DB=mysql
#  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - mysql -e 'create database portfolio_test'
  - psql -c 'create database portfolio_test' -U postgres
